#!/bin/bash
# This is a Tmux script that handles starting up tintin with all of the Aardwolf settings.
# You will need to change the -x <column> and -y <row> size
# Also change 'AARD_PATH' to whatever directory you use for the settings.
# Requires Tmux 1.5 - See http://theixle.dyndns.org for a download link.

export AARD_PATH=$(pwd)

# Reset all pane files
echo "Chats" > $AARD_PATH/Aardwolf-chats
echo "Chars in the Room" > $AARD_PATH/chars
echo "Minimap" > $AARD_PATH/minimap
echo "Group Info" > $AARD_PATH/group
echo "Quest Info" > $AARD_PATH/quest
echo "Affects" > $AARD_PATH/affects

tmux kill-session -t aardwolf
tmux new-session -d -s aardwolf -x 189 -y 47
tmux splitw -h -l 159 'tail -fs .1 $AARD_PATH/Aardwolf-chats'
tmux splitw -v -l 37 'tt++ -G $AARD_PATH/setup.tin;bash -i'
tmux splitw -h -l 68 'tail -fs .1 $AARD_PATH/chars'
tmux selectp -t 0
tmux splitw -v -l 22 'tail -fs .1 $AARD_PATH/minimap'
tmux selectp -t 0
tmux splitw -v -l 14 'tail -fs .1 $AARD_PATH/group'
tmux selectp -t 5
tmux splitw -v -l 20 'tail -fs .1 $AARD_PATH/quest'
tmux selectp -t 4
tmux attach-session -t aardwolf
